### ISSUE TITLE
NET0407 Table 1 Requirements not tested in astm.netrid.v22a.NominalBehavior

### ISSUE THREAD

**Issue by wing-utm-sharing-airspace** [interuss/monitoring#858] opened 2024-12-04 18:55 UTC
**Observed behavior**
In scenarios.astm.netrid.v22a.NominalBehavior, NET0407 requirements are not being verified during the "Observer polling" step.

We're currently interested in:
NET0470,Table1,1
NET0470,Table1,1a
NET0470,Table1,9
NET0470,Table1,19
NET0470,Table1,20

Example Test Artifacts: [aac5c156-dc1c-4ef4-934a-64c50ea5226f.zip](https://github.com/user-attachments/files/18000759/aac5c156-dc1c-4ef4-934a-64c50ea5226f.zip)

**Test check**
Screenshot of our USS populating the relevant fields:
![image](https://github.com/user-attachments/assets/814baf1c-3339-4299-8504-f219a35a9b4c)
Scenario 31 Step 759 in attached test artifacts.

**Difference from expected behavior**
Our USS is populating the UAS ID, Operator ID, speed, and track when our observer is polled so we believe the NET0407 requirements in the `phase1_requirements/wing.html` file should be marked as "passed" where this test report shows them as "not tested".
![Screenshot 2024-12-04 at 10 53 43 AM](https://github.com/user-attachments/assets/26030991-f938-46f0-aff9-4982666d5473)

**Comment by BenjaminPelletier** [comment] 2024-12-04 21:23
Duplicate of #857, I believe.  Feel free to reopen if it is actually not a duplicate.

**Closed by BenjaminPelletier** 2024-12-04 21:23 UTC
Labels: duplicate, automated-testing, test-scenario-behavior
