### ISSUE TITLE
FlightIntentValidation's operational intent(s) are not long enough

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#648] opened 2024-04-22 01:57 UTC
**report.json is not attached because**
Screenshot + supplemental information should be sufficient:

<img width="1561" alt="Screenshot 2024-04-21 at 6 41 36 PM" src="https://github.com/interuss/monitoring/assets/11224086/ff43cd4c-e425-4344-9e08-b967a0c9237c">

monitoring repo commit hash: befe56ff837d3f4d449e0e18d66d917a79db03a1

**Test check**
The ones for [successful planning](https://github.com/interuss/monitoring/blob/befe56ff837d3f4d449e0e18d66d917a79db03a1/monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.md#plan)

**Difference from expected behavior**
The flight plan uss_qualifier requested for the should-be-successful planning activity had an end time prior to the time of request (see two red arrows), and therefore the USS under test correctly rejected the request.  This is presumably because the first part of the test took longer than the duration of the configured flight intent test data.  Ideally, the reusable test steps should detect when the flight plan they want to request and expect to be valid is actually invalid (specifically, having an end time in the past in this case).  But also, likely the duration of the flight intents for this scenario in the test data should be increased to allow for longer test execution.

**Additional context**
Encountered while testing multiple real-world participant systems

**Comment by BenjaminPelletier** [comment] 2024-04-22 02:10
This appears to happen in the GetOpResponseDataValidationByUSS scenario as well
[s59.html.zip](https://github.com/interuss/monitoring/files/15056311/s59.html.zip)

**Comment by Shastick** [comment] 2024-04-22 15:46
Sidenote: the [FlightIntentValidation scenario](https://github.com/interuss/monitoring/blob/e29f1b847402d5061575f098e2695cd419b20a44/monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py#L277) does submit a recently expired plan by design, so we probably need to provide a way to skip the check when the scenario developer requires it.

**Comment by BenjaminPelletier** [comment] 2024-04-24 20:24
This issue still persists and is preventing tests because ConflictEqualPriorityNotPermitted still [renders](https://github.com/interuss/monitoring/blob/2a9b6a16051685000c408867d748a36ed069a358/monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.py#L177) flight intents when the scenario is instantiated rather than when it is run, so TimeOfEvaluation (and StartOfTestScenario) are not populated correctly.

Additionally, the changes in #650 apparently did not detect the attempt to plan a flight entirely in the past; we should check why that might not have been.

**Comment by Shastick** [comment] 2024-04-25 07:34
It looks like it would be worth starting to rely only on the `FlightInfoTemplate`. At least in `ConflictEqualPriorityNotPermitted` that should be easy as it is available already. 

> Additionally, the changes in https://github.com/interuss/monitoring/pull/650 apparently did not detect the attempt to plan a flight entirely in the past; we should check why that might not have been.

I don't see an obvious reason for that: possibly a little mistake somewhere causes `end_time_of` to return a `None` when it should not. 

I'll be looking into this today or tomorrow.

**Comment by Shastick** [comment] 2024-04-30 06:35
#666 will possibly solve this, or make it easier to fix it if the issue is still present. Waiting until it is merged.

**Comment by Shastick** [comment] 2024-05-08 06:40
At least for the `FlightIntentValidation`, the involved times should now be correct, as the new flight info templates are now used and properly resolved.

Regarding the possibility of a bug in the validation logic: I confirmed that there is no obvious bug there by disabling the bypass flag for a scenario that creates an operational intent reference in the past and observed a raised exception.

**Closed by Shastick** 2024-05-08 06:40 UTC
Labels: automated-testing, P1, test-scenario-behavior
